### ISSUE TITLE
Missing include headers for love-11.4-ios release?

### ISSUE THREAD

**Issue by SugarRayLua** [love2d/love#1867]
Hello. I am a newbie Love2D user and am trying to build 11.4 for my iPad OS 11.1. I followed all of the instructions on the love2d wiki except for the part that indicated if there were no "include" folder to download it from the specified link on the wiki. The love-11.4-ios release does not have any "include" folder and the specified link does not have an "include" folder for the love-11.4 release (only library and include folder for the love 11.3 release for iOS). Without the "include" folder of headers for the love-11.4-ios release I was able to build love2D for iPad OS 11.1 with Xcode 14 but it was not able to run all of my newer .love files that I'm able to run using love2d on my Mac. I was wondering therefore if love-11.4-iOS release is suppose to also include header files and that is why my iPad OS installation isn't running all of my .love files like my Mac version is? 

Thanks :-)

**Comment by slime73** [comment]
The wiki instructions are a bit out of date - there isn't a separate `include` folder anymore for love 11.4.

> it was not able to run all of my newer .love files that I'm able to run using love2d on my Mac.

What sort of problems have you been running into when trying to run them?

**Comment by SugarRayLua** [comment]
Thanks for your prompt response and clarifying, @slime73.

I went back and rebuilt the iOS using minimum iOS target of 15.6 which helped some.

I also realized the problems that I was having were probably love library/module specific. I was interested in the 3D libraries and tried the g3d library as seemed the simplest and actively being maintained. I tried both one of the g3d library developers examples and a published love game based on the g3d library-- both ran fine with Love2d 11.4 on my Mac but not on my iPad Pro with the latest iPad OS (16.1). On my iPad, the apps produced the following errors:

**g3d**
Example: First Person Test

Error

Error validating pixel shader code:
Line 18: ERROR: '-' :  wrong operand types: no operation '-' exists that takes a left-hand operand of type ' const int' and a right operand of type ' temp mediump float' (or there is no acceptable conversion)
Line 18: ERROR: '' : missing #endif 
Line 18: ERROR: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'newShader'
g3d/shader.lua:33: in main chunk
[C]: in function 'require'
g3d/model.lua:27: in main chunk
[C]: in function 'require'
g3d/init.lua:23: in main chunk
[C]: in function 'require'
main.lua:6: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

Separate example: Hoarder’s Horrible House of Stuff

*Initial screen loads but then when tap to start the game get*

Error

Error validating vertex shader code:
Line 7: ERROR: 'uniform' :  cannot initialize this type of qualifier  
ERROR: 1 compilation errors.  No code generated.


Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'newShader'
libs/g3d/camera.lua:26: in function 'initialize'
libs/middleclass.lua:140: in function 'new'
libs/g3d/sun.lua:5: in function 'initialize'
libs/middleclass.lua:140: in function 'new'
game.lua:238: in function 'createCamera'
game.lua:43: in function 'load'
main.lua:223: in function 'setgamestate'
menu.lua:56: in function 'update'
main.lua:84: in function 'update'
[love "callbacks.lua"]:162: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

Yet, much older, non-3D games run fine on the love2d-ios-11.4 build (e.g. "blackjack.love").

Unexpectedly, the more complex 3D love library/module "3DreamMachine"'s demo programs do run on my iPad love2d-ios-11.4 build (although one of the examples in the demo doesn't render everything correctly).

As a newbie Love2D user, I had thought that with all installations of the same version of Love2d utilizing the same Lua version and SDL libraries that any program able to run on Love2D on one machine/OS would be able to run the same on any other machine/OS which does not seem to be the case (at least for Love2D 3D graphic libraries). Thus, I'll contact the specific Love2D library maintainers if I have further difficulty with using their library on my iPad iOS installation of Love 2D. 

Have a good rest of your weekend.

**Comment by SugarRayLua** [comment]
(P.S., the simpler "Earth and Moon" demo from the g3d module work fine on the iPad running love-11.4-ios)

**Comment by slime73** [comment]
I updated that wiki page so it's more accurate for 11.4's iOS libraries now.

For those shaders, on mobile devices love uses OpenGL ES, whose shading language is a little more strict and limited compared to desktop OpenGL.

You can write shaders that are compatible with both as long as a few things are kept in mind. For example uniform/extern variables can't be initialized to constant values in the shader code, you have to use `Shader:send` instead. And there's no implicit conversion between float and int variables in OpenGL ES' shading language - typically you'd want to stick with floats most places, but when you do need to use ints you can explicitly cast between float and int:
```glsl
float myFloatVariable = float(myIntVariable);
int myNewIntVariable = int(myFloatVariable);
```

**Comment by SugarRayLua** [comment]
Thank you for the additional tips!
