### ISSUE TITLE
Love 11.1 does not build on lua 5.4.3

### ISSUE THREAD

**Issue by slime73** [love2d/love#1413]
**[Original report](https://bitbucket.org/rude/love/issue/1408) by Jeremy Newton (Bitbucket: [Mystro256](https://bitbucket.org/Mystro256), GitHub: [Mystro256](https://github.com/Mystro256)).**

----------------------------------------

Hi I'm the love package maintainer for Fedora/EPEL.

I was trying to build love 11.1 for Fedora but it seems it can't compile against lua 5.3.4.

Luajit works just fine, it seems to only affect lua, which is what I use to build love for PPC/s390x platforms.

The build error I get is (full ppc64 build log attached):

```
#!c++

love.cpp: In function 'DoneAction runlove(int, char**, int&)':
love.cpp:217:24: error: too few arguments to function 'int lua_resume(lua_State*, lua_State*, int)'
  while (lua_resume(L, 0) == LUA_YIELD)
                        ^
In file included from love.cpp:29:
/usr/include/lua.h:291:15: note: declared here
 LUA_API int  (lua_resume)     (lua_State *L, lua_State *from, int narg);
               ^~~~~~~~~~
```
